files:
  include:
    - 'src/**/*.scss'
  ignore:
rules:
  indentation:
    - 2
    -
      size: 4
  single-line-per-selector: 2
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: camelcase
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: camelcase
  force-pseudo-nesting: 0
  leading-zero:
    - 2
    -
      include: true
  nesting-depth:
    - 2
    -
      max-depth: 4
  force-attribute-nesting:
    - 0
  no-qualifying-elements:
    -
      allow-element-with-attribute: true
